version: '3.8'

services:
  api:
    build: .
    container_name: booking_app_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./sql_app.db